CREATE TABLE Users
(
    UserId UNIQUEIDENTIFIER NOT NULL,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    Role  NVARCHAR NOT NULL,
)

CREATE TABLE Vehicles
(
    VehicleId INT IDENTITY PRIMARY KEY,
    RegistrationNumber NVARCHAR(50) NOT NULL,
    Description NVARCHAR(50) NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
)

CREATE TABLE ParkingSpots
(
    ParkingSpotId INT IDENTITY PRIMARY KEY,
    Description NVARCHAR(50) NULL,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    CreatedBy UNIQUEIDENTIFIER NOT NULL,
)

CREATE TABLE Reservations
(
    ReservationId INT IDENTITY PRIMARY KEY,
    ParkingSpotId  INT NOT NULL,
    VehicleId INT NOT NULL,
    DateTimeFrom DATETIME NOT NULL,
    DateTimeTo DATETIME NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
)