CREATE TABLE Users
(
    UserId UNIQUEIDENTIFIER NOT NULL,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    Role  NVARCHAR NOT NULL,
)

CREATE TABLE Vehicles
(
    VehicleId INT IDENTITY PRIMARY KEY,
    RegistrationNumber NVARCHAR NOT NULL,
    Description NVARCHAR NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
)

CREATE TABLE Reservations
(
    ReservationId INT IDENTITY PRIMARY KEY,
    VehicleId INT NOT NULL,
    DateTimeFrom DATETIME NOT NULL,
    DateTimeTo DATETIME NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
)